blank_issues_enabled: false
contact_links:
  - name: Questions and usage help
    url: https://github.com/volten-gpu/volten/discussions/categories/q-a
    about: Ask usage questions or get help with Volten.
